### ISSUE TITLE
A way to map object property with a Id column

### ISSUE THREAD

**Issue by buinauskas** [henkmollema/Dapper-FluentMap#71]
Considering these models:
``` csharp
public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Category Category { get; set; }
}

public class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

And the following `EntityMap` configuration:
``` csharp
public class ProductMap : EntityMap<Product>
{
    public ProductMap()
    {
        Map(p => p.Id).ToColumn("ProductId", false);
        Map(p => p.Name).ToColumn("ProductName", false);
        Map(p => p.Category.Id).ToColumn("CategoryId", false);
        Map(p => p.Category.Name).ToColumn("CategoryName", false);
    }
}
```

Is there a way to map result of a SQL query with such a structure to my model?
``` sql
SELECT ProductId, ProductName, CategoryId, CategoryName
FROM dbo.Product;
```

Currently I'm getting an exception that a duplicate mapping for `Id` column has been declared:
```
System.Exception
  HResult=0x80131500
  Message=Duplicate mapping detected. Property 'Id' is already mapped to column 'Id'.
  Source=Dapper.FluentMap
  StackTrace:
   at Dapper.FluentMap.Mapping.EntityMapBase`2.ThrowIfDuplicateMapping(IPropertyMap map)
   at Dapper.FluentMap.Mapping.EntityMapBase`2.Map(Expression`1 expression)
   at IDAR.Domain.Tests.ProductMap..ctor() in C:\Users\buina\source\repos\Learning\Learning.Domain.Tests\Dummy.cs:line 45
   at IDAR.Domain.Tests.Dummy.NestedProperty() in C:\Users\buina\source\repos\Learning\Learning.Domain.Tests\Dummy.cs:line 13
```

**Comment by henkmollema** [comment]
You should create a separate mapping for the `Category` class:

```
public class CategoryMap : EntityMap<Category>
{
    public CategoryMap ()
    {
        Map(p => p.Id).ToColumn("CategoryId", false);
        Map(p => p.Name).ToColumn("CategoryName", false);
    }
}
```
